#!/usr/bin/env node
/* Decision trace oracle.  Source is evaluated unchanged from frontend/.
 * RNG rule: seed before evaluation, immediately after every getPlayer(), and
 * immediately before every Driver() construction; construction-only FX draws
 * therefore cannot perturb driver decisions. */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { JSDOM } from 'jsdom';

const here=path.dirname(fileURLToPath(import.meta.url)), repo=path.resolve(here,'../../..'), frontend=path.join(repo,'frontend');
const argv=process.argv.slice(2),args={};for(let i=0;i<argv.length;i++)if(argv[i].startsWith('--')){const key=argv[i].slice(2),value=argv[i+1];args[key]=value&&!value.startsWith('--')?(i++,value):true;}
const ticks=Number(args.ticks||5000), seed=Number(args.seed||12345);
function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
/* Pinned reference stream: the JS engine driving the goldens. Swift's ParityRNG must match these
 * same vectors (P2 gate), so a Node/JS engine change or a bad port is caught here first. */
const RNG_VECTOR={1:['0.62707394058816135','0.00273572118021548','0.52744703995995224','0.98105096747167408','0.96837789821438491','0.28110350295901299','0.61283886060118675','0.72074314113706350'],42:['0.60110375192016363','0.44829055899754167','0.85246579349040985','0.66973404143936932','0.17481389874592423','0.52659254218451679','0.27322799433022738','0.62474465393461287'],12648430:['0.02114150836132467','0.66610999661497772','0.77997141960076988','0.73958444688469172','0.10705656302161515','0.50101924454793334','0.14595783082768321','0.36372411437332630']};
function assertRng(){for(const seed of Object.keys(RNG_VECTOR)){const want=RNG_VECTOR[seed],r=rng(Number(seed)),got=[];for(let i=0;i<want.length;i++)got.push(r().toFixed(17));if(JSON.stringify(got)!==JSON.stringify(want)){console.error(`RNG MISMATCH seed=${seed}\n got ${got}\nwant ${want}`);process.exit(3)}}}
function profile(){const beats=[],bars=[],sections=[],tatums=[],segments=[];for(let i=0;i<60;i++){beats.push({which:i,start:i*.5,duration:.5,confidence:.9,indexInParent:i%4,section:Math.floor(i/15),pitches:[1,0,0,0,0,0,0,0,0,0,0,0],timbre:Array(12).fill(i%5),bar_length_beats:4,beat_in_bar:i%4});}for(let i=0;i<15;i++)bars.push({which:i,start:i*2,duration:2,confidence:.9});for(let i=0;i<4;i++)sections.push({which:i,start:i*7.5,duration:7.5,confidence:.9});for(let i=0;i<240;i++){tatums.push({which:i,start:i*.125,duration:.125,confidence:.9});segments.push({which:i,start:i*.125,duration:.125,confidence:.9,pitches:Array(12).fill((i%7)/7),timbre:Array(12).fill(i%5),loudness_start:-20,loudness_max:-10});}const pairs=beats.map((_,i)=>(i+16)%60), edges=[];const loops={};for(let i=0;i<60;i++){if(i>=16){const e={target:i-16,similarity:.9,span:-16,direction:'backward',section_match:false,source:i};edges.push(e);(loops[i]??=[]).push(e)}}return {status:'complete',info:{url:'http://parity.test/audio'},audio_summary:{duration:30},title:'selftest',artist:'oracle',analysis:{sections,bars,beats,tatums,segments,eternal_loop_candidates:loops,loop_candidates:edges,canon_alignment:{pairs,pair_similarity:beats.map(()=>.9),offset:16,loop_candidates:edges},canon_candidates:edges,global_voice_offsets:[4,8,12,16,20,24]}};}
function clock(w){let now=0,id=1,q=[];const add=(fn,ms)=>{const x={id:id++,fn,at:now+Number(ms||0),dead:false};q.push(x);return x.id};w.setTimeout=add;w.clearTimeout=x=>{const t=q.find(z=>z.id===x);if(t)t.dead=true};w.setInterval=(f,m)=>add(function r(){f();add(r,m)},m);w.clearInterval=w.clearTimeout;w.Date.now=()=>now;w.performance.now=()=>now;return{step(){q.sort((a,b)=>a.at-b.at||a.id-b.id);while(q.length&&q[0].dead)q.shift();if(!q.length)return false;const t=q.shift();now=t.at;t.fn();return true;},now:()=>now};}
function audio(w,c,starts){let nid=0;class N{constructor(){this.id=++nid;this.gain=param();this.frequency=param();this.Q=param();this.delayTime=param();this.pan=param();this.playbackRate=param();}connect(d){this.dest=d;return d}disconnect(){}start(_when,offset,duration){starts.push({node:this.id,dest:this.dest?.id??null,offset,duration})}stop(){}}function param(){return{value:1,cancelScheduledValues(){},setValueAtTime(v){this.value=v}}}class C{constructor(){this.destination=new N;this.sampleRate=8;this.state='running'}get currentTime(){return c.now()/1000}resume(){return Promise.resolve()}createAnalyser(){let n=new N;n.getByteFrequencyData=a=>a.fill(0);return n}createGain(){return new N}createGainNode(){return new N}createBiquadFilter(){return new N}createChannelSplitter(){return new N}createChannelMerger(){return new N}createDynamicsCompressor(){let n=new N;for(const k of ['threshold','knee','ratio','attack','release'])n[k]=param();return n}createWaveShaper(){return new N}createDelay(){return new N}createConvolver(){return new N}createOscillator(){return new N}createStereoPanner(){return new N}createBufferSource(){return new N}createBuffer(ch,l){return{numberOfChannels:ch,getChannelData(){return new Float32Array(l)}}}decodeAudioData(_x,ok){ok(this.createBuffer(1,8))}}w.AudioContext=w.webkitAudioContext=C;}
function raphael(w){const x={attr(){return this},animate(){return this},remove(){},hide(){},show(){},toFront(){return this},toBack(){return this},insertBefore(){return this},insertAfter(){return this},stop(){return this},transform(){return this},data(){return this},getBBox(){return{x:0,y:0,width:0,height:0}},glow(){return this},mousedown(){return this},mouseup(){return this},mouseover(){return this},mouseout(){return this},click(){return this},drag(){return this},getTotalLength(){return 1},getPointAtLength(){return{x:0,y:0}}};const p={rect:()=>({...x}),circle:()=>({...x}),path:()=>({...x}),text:()=>({...x}),set:()=>[],setSize(){},clear(){},remove(){}};w.Raphael=()=>p;}
function loadProfile(p){if(!p)return profile();const x=JSON.parse(fs.readFileSync(p,'utf8'));return x.response?.track||x.track||x;}
function safe(v){return JSON.parse(JSON.stringify(v,(k,x)=>k==='track'||k==='parent'||k==='next'||k==='previous'||k==='beat'?undefined:x));}
function run(one){const starts=[], dom=new JSDOM(fs.readFileSync(path.join(frontend,'harmonizer.html'),'utf8'),{url:`http://parity.test/?trid=${encodeURIComponent(one.fixture)}`,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,cl=clock(w);audio(w,cl,starts);raphael(w);w.XMLHttpRequest=class{open(){}send(){this.response=new ArrayBuffer(8);this.onload?.()} };let draws=0, random=rng(one.seed);w.Math.random=()=>{draws++;return random()};w.mode=one.mode;w.canonVoiceCount=one.voices;w.harmonizerBaseAudioOnly=false;w.harmonizerRLModel=one.policy==='baseline'?null:(one.policy==='heuristic'?{type:'empty'}:JSON.parse(fs.readFileSync(one.gbrt,'utf8')));w.requestAnimationFrame=()=>0;w.cancelAnimationFrame=()=>{};w.fetch=async()=>({ok:true,json:async()=>({})});w.console={log(){},warn(){},error(){}};const track=loadProfile(one.profile);w.$=undefined;const ctx=dom.getInternalVMContext();const src=(...p)=>fs.readFileSync(path.join(frontend,...p),'utf8');for(const f of [['js/jquery-3.7.1.min.js'],['js/underscore-min.js'],['js/raphael-min.js'],['jremix.js'],['js/eternal_jukebox_engine.js'],['js/persistent-player.js'],['js/visualizer.js']])new vm.Script(src(...f),{filename:path.join(frontend,...f)}).runInContext(ctx);raphael(w);
// lexical bridge/wrappers execute in the source realm without editing source files.
w.__track=track;w.__seed=one.seed;new vm.Script(`(function(){var nativeCreate=createJRemixer; createJRemixer=function(){var r=nativeCreate.apply(this,arguments),g=r.getPlayer;r.getPlayer=function(){var p=g.apply(r,arguments); Math.random=window.__randomReset(); return p};return r};var nativeDriver=Driver;Driver=function(p){Math.random=window.__randomReset();return nativeDriver(p)}; $.getJSON=function(_u,cb){cb({response:{status:{code:0},track:window.__track}});return{fail:function(){return this}}};})()`).runInContext(ctx);w.__randomReset=()=>{random=rng(one.seed);return()=>{draws++;return random()}};
/* FINDING 12. `visualizer.js:387` declares `var mode = "canon"` at script scope, which lands on
 * `window.mode` and overwrites the `w.mode = one.mode` set above; `init()` then re-derives `mode`
 * from `document.body[data-mode]`, which the shipped page hard-codes to "canon". So every trace in
 * the committed corpus runs CanonDriver regardless of its filename. `--mode-aware` restores the
 * selection the harness always intended by writing the requested mode into the body attribute
 * before `onload` runs `init()`. It is opt-in so the M0-signed-off corpus and MANIFEST stay
 * byte-identical; the moded corpus lives in its own directory. */
if(one.modeAware){w.document.body.setAttribute('data-mode',one.mode);w.mode=one.mode;}
/* `window.harmonizerLoopEnabled` is set by an inline script in `harmonizer.html`, which
 * `runScripts:'outside-only'` never executes, so every trace runs with looping off. That is
 * invisible for canon/jukebox/eternal - canon wraps inside `chooseCanonNextIndex` and the orbit
 * drivers never reach the last beat - but autocrooner steps one beat per tick and stops dead at the
 * end of the track, so a 5,000-tick autocrooner trace cannot be produced with looping off. This
 * flag turns it on for the moded corpus's autocrooner runs only; it is opt-in so the committed
 * corpus stays byte-identical. */
if(one.loopEnabled){w.harmonizerLoopEnabled=true;}
w.onload(new w.Event('load'));while(!w.masterQs&&cl.step()){}if(!w.masterQs)throw Error('track did not become ready');let player=w.harmonizerActivePlayer, speed=1;const ss=player.setSpeedFactor;player.setSpeedFactor=function(x){speed=x;return ss.apply(this,arguments)};const traces=[],raw=[],gainMap=new Map(),native=player.playQ;let prior=null, priorDraw=0;player.playQ=function(q){if(prior){prior.draws=draws-priorDraw;traces.push(prior)}priorDraw=draws;const at=starts.length;const ret=native.apply(this,arguments), obs=starts.slice(at), states=w.currentVoiceStates||[];let main=false, voices=states.map(s=>({beat:s.beatIdx,restart:false,offset:s.barOffset}));const pending=[];const candidates=off=>{const c=[];if(off===q.start)c.push('main');states.forEach((s,i)=>{const b=q.track.analysis.beats[s.beatIdx];if(b&&off===b.start)c.push(i)});return c};for(const o of obs){const targets=candidates(o.offset);let key=gainMap.get(o.dest);if(key===undefined&&targets.length===1){key=targets[0];gainMap.set(o.dest,key)}if(key==='main')main=true;else if(Number.isInteger(key))voices[key].restart=true;else pending.push({o,offset:o.offset})}
/* When several voices start on the same beat the destination alone cannot tell them apart. Sources
 * are created voice by voice within a playQ call, so if the observation count at an offset equals
 * the number of voices sitting on that beat they match one-to-one in order. */
const byOffset=new Map();for(const p of pending){if(!byOffset.has(p.offset))byOffset.set(p.offset,[]);byOffset.get(p.offset).push(p)}
for(const [offset,group] of byOffset){const cand=candidates(offset);if(cand.length!==group.length)continue;group.forEach((p,i)=>{const v=cand[i];gainMap.set(p.o.dest,v);if(v==='main')main=true;else voices[v].restart=true})}
for(const p of pending){if(gainMap.get(p.o.dest)===undefined)raw.push({tick:traces.length,q:q.which,observation:p.o,targets:candidates(p.offset)})}
prior={tick:traces.length,mainBeat:q.which,mainRestart:main,voices,rate:speed,draws:0,delay:ret};return ret};
const actual=JSON.parse(new vm.Script(`JSON.stringify({settings:getLoopSettingsForMode(mode),offsets:typeof canonVoiceOffsetsForDriver==='undefined'?null:canonVoiceOffsetsForDriver,gains:masterQs.map(function(q){return{otherGain:q.otherGain,others:(q.others||[]).map(function(){return q.otherGain})}})})`).runInContext(ctx));const beatsSnap=(w.masterQs||[]).map((b,i)=>({index:i,section:b.section,indexInParent:b.indexInParent,start:b.start,duration:b.duration,confidence:b.confidence,other:b.other?.which??null,others:(b.others||[]).map(x=>x?.which??null),otherGain:b.otherGain,neighbors:(b.neighbors||[]).map(n=>({beat:n.beat?.which,distance:n.distance})),goodNeighbors:(b.goodNeighbors||[]).map(n=>({beat:n.beat?.which,distance:n.distance}))}));const loopGraphSnap=safe(w._jukeboxLoopGraph||{});
w.driver.start();while(traces.length<one.ticks&&cl.step()){}if(prior&&traces.length<one.ticks){prior.draws=draws-priorDraw;traces.push(prior)}if(traces.length!==one.ticks)throw Error(`only ${traces.length}/${one.ticks} ticks executed`);const prep={fixture:one.fixture,mode:one.mode,voices:one.voices,policy:one.policy,seed:one.seed,beats:beatsSnap,loopGraph:loopGraphSnap,voiceGains:actual.gains,voiceOffsets:actual.offsets,effectiveSettings:actual.settings,keys:{beat:['index','section','indexInParent','start','duration','confidence','other','others','otherGain','neighbors','goodNeighbors'],loopGraph:'window._jukeboxLoopGraph',voiceGains:'masterQs[].otherGain/masterQs[].others',voiceOffsets:'canonVoiceOffsetsForDriver',effectiveSettings:'getLoopSettingsForMode(mode)'}};const result={traces,raw,prep};try{dom.window.close()}catch(_e){}return result;}
function write(one,out){const r=run(one);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,r.traces.map(x=>JSON.stringify(x)).join('\n')+'\n');if(r.raw.length)fs.writeFileSync(out+'.ambiguous.json',JSON.stringify(r.raw,null,2)+'\n');return r;}
const MODES=[['canon',2],['canon',3],['canon',5],['canon',8],['jukebox',2],['eternal',2],['autocrooner',2]];
const DEFAULT_GBRT=path.join(repo,'rl_models','model.json');
const gbrtModel=args['gbrt-model']||(fs.existsSync(DEFAULT_GBRT)?DEFAULT_GBRT:null);
function seedList(){if(args.seeds)return String(args.seeds).split(',').map(x=>Number(x.trim())).filter(x=>!Number.isNaN(x));if(args.seed)return[Number(args.seed)];return[1,42,0xC0FFEE];}
function policyList(){return gbrtModel?['baseline','heuristic','gbrt']:['baseline','heuristic'];}
const parity=path.resolve(here,'..');
function profileDir(out){const local=path.join(out,'profiles');return fs.existsSync(local)&&fs.readdirSync(local).some(x=>x.endsWith('.json'))?local:path.join(parity,'fixtures','profiles');}
let prepConflicts=0;
function writePrep(prep,out){const body={...prep};delete body.policy;delete body.seed;const p=path.join(out,'prep',`${prep.fixture}__${prep.mode}-v${prep.voices}.json`);fs.mkdirSync(path.dirname(p),{recursive:true});const text=JSON.stringify(body,null,2)+'\n';if(fs.existsSync(p)&&fs.readFileSync(p,'utf8')!==text){prepConflicts++;console.error(`PREP CONFLICT ${p}: prep depends on policy/seed`)}fs.writeFileSync(p,text);return p;}
function matrixOne(out){const pdir=profileDir(out);if(!fs.existsSync(pdir))throw Error(`no profiles at ${pdir}`);const names=fs.readdirSync(pdir).filter(x=>x.endsWith('.json')).sort();const fixtures=args.fixture?names.filter(x=>x.replace(/\.json$/,'')===args.fixture):names;const seeds=seedList(),policies=policyList();const modes=args.modes?MODES.filter(m=>String(args.modes).split(',').includes(`${m[0]}:${m[1]}`)):MODES;let count=0;for(const f of fixtures){const id=f.replace(/\.json$/,''),profile=path.join(pdir,f);for(const [mode,voices] of modes)for(const policy of policies)for(const seedValue of seeds){const file=path.join(out,'traces',id,`${mode}-v${voices}-${policy}-s${seedValue}.jsonl`);const r=write({profile,mode,voices,policy,seed:seedValue,ticks,fixture:id,gbrt:gbrtModel,modeAware:!!args['mode-aware'],loopEnabled:!!args.loop},file);writePrep(r.prep,out);count++;}}if(prepConflicts)console.error(`PREP CONFLICTS: ${prepConflicts}`);return count;}
/* Each trace builds a fresh JSDOM and evaluates the whole visualizer, which is not fully reclaimed;
 * ~800 traces in one process exhausts the V8 heap. Run each fixture in its own short-lived child so
 * the heap goes back to the OS between fixtures. Children are deterministic, so the result is the
 * same as one process would produce. */
/* Windows occasionally fails to start a fixture child under this workload with
 * STATUS_DLL_INIT_FAILED (0xC0000142) after a dozen or so spawns; it is a launch failure, not a
 * divergence, and the child is deterministic, so a bounded retry is safe and keeps a 15-minute
 * batch from being thrown away on the last fixture. A real failure still surfaces after 3 tries. */
const SPAWN_ATTEMPTS=3;
function matrix(out){if(args.fixture)return matrixOne(out);const pdir=profileDir(out);if(!fs.existsSync(pdir))throw Error(`no profiles at ${pdir}`);const ids=fs.readdirSync(pdir).filter(x=>x.endsWith('.json')).map(x=>x.replace(/\.json$/,'')).sort();const seeds=seedList();let count=0;for(const id of ids){const cargs=[fileURLToPath(import.meta.url),'--out',out,'--ticks',String(ticks),'--seeds',seeds.join(','),'--fixture',id];if(gbrtModel)cargs.push('--gbrt-model',gbrtModel);if(args['mode-aware'])cargs.push('--mode-aware');if(args.loop)cargs.push('--loop');if(args.modes)cargs.push('--modes',args.modes);console.log(`matrix ${id} ...`);let res=null;for(let attempt=1;attempt<=SPAWN_ATTEMPTS;attempt++){res=spawnSync(process.execPath,cargs,{stdio:'inherit'});if(res.status===0)break;console.error(`matrix ${id}: child exit ${res.status}, attempt ${attempt}/${SPAWN_ATTEMPTS}`);}if(res.status!==0)throw Error(`matrix failed for ${id} (status ${res.status})`);count+=(args.modes?MODES.filter(m=>String(args.modes).split(',').includes(`${m[0]}:${m[1]}`)):MODES).length*policyList().length*seeds.length;}return count;}
function sameTree(a,b){const files=d=>['traces','prep'].flatMap(root=>fs.existsSync(path.join(d,root))?fs.readdirSync(path.join(d,root),{recursive:true}).filter(x=>fs.statSync(path.join(d,root,x)).isFile()).map(x=>path.join(root,x)):[]).sort();const aa=files(a),bb=files(b);if(JSON.stringify(aa)!==JSON.stringify(bb))return aa.find((x,i)=>x!==bb[i])||bb.find((x,i)=>x!==aa[i]);for(const f of aa)if(!fs.readFileSync(path.join(a,f)).equals(fs.readFileSync(path.join(b,f))))return f;return null}
function main(){if(args['rng-vector']){for(const seed of Object.keys(RNG_VECTOR)){const r=rng(Number(seed)),out=[];for(let i=0;i<8;i++)out.push(r().toFixed(17));console.log(seed,out.join(' '))}return}assertRng();if(args.check){const tempA=fs.mkdtempSync(path.join(here,'trace-a-')),tempB=fs.mkdtempSync(path.join(here,'trace-b-'));try{const na=matrix(tempA),nb=matrix(tempB);if(na!==nb){console.error(`CHECK FAIL: matrix size ${na} != ${nb}`);process.exitCode=1;return}const diff=sameTree(tempA,tempB);if(diff){console.error(`CHECK FAIL: two runs differ at ${diff}`);process.exitCode=1;return}console.log(`CHECK OK: ${na} traces identical across two runs`);const fixtures=path.join(parity,'fixtures');if(fs.existsSync(path.join(fixtures,'traces'))){const cdiff=sameTree(fixtures,tempA);if(cdiff){console.error(`CHECK FAIL: committed fixtures differ at ${cdiff}`);process.exitCode=1}else console.log('CHECK OK: committed fixtures match a fresh run')}}finally{fs.rmSync(tempA,{recursive:true,force:true});fs.rmSync(tempB,{recursive:true,force:true})}return}if(args.profile||args.mode){if(!args.mode||!args.out)throw Error('single run needs --mode and --out');if(args.policy==='gbrt'&&!gbrtModel){console.error('SKIP gbrt: --gbrt-model is required');return}const r=write({profile:args.profile,mode:args.mode,voices:Number(args.voices||2),policy:args.policy||'baseline',seed,ticks,fixture:path.basename(args.profile||'selftest').replace(/\.json$/,''),gbrt:gbrtModel,modeAware:!!args['mode-aware'],loopEnabled:!!args.loop},args.out);console.log(JSON.stringify(r.prep,null,2));return}const out=args.out;if(!out)throw Error('--out is required');const n=matrix(out);if(!args.fixture)console.log(`matrix: ${n} traces under ${out}`)}
main();
